/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bd.GestorPersistencia;
import bd.UtilitatPersistenciaException; 

import java.awt.Component;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListCellRenderer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import empresa.Empresa;
import empresa.Incidencia;
import empresa.IncidenciaEstandar;
import empresa.IncidenciaUrgent;

/**
 *
 * @author 
 */
public class GestioBD extends javax.swing.JFrame {
    
    
    GestorPersistencia bd;
    ModelTaulaList mEmpreses, mIncidenciesEmpresa;
    ModelTaulaList mIncidencies, mConsulta;
    Empresa empresaAMantenir=null;
    Incidencia incidenciaAMantenir=null;
    
    
    public GestioBD(GestorPersistencia bd){
        
        this.bd=bd;
        try {
            this.bd.iniciar();
            this.bd.obrir();
        } catch (UtilitatPersistenciaException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        
        adaptarCombosEmpreses();
        
        afegirListenersLiniaSeleccionada();
        
    }
    
    /**
     * Creates new form GestioBD
     */
    public GestioBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jTpnlPrincipal = new javax.swing.JTabbedPane();
        jPnlEmpreses = new javax.swing.JPanel();
        jScrPnlEmpreses = new javax.swing.JScrollPane();
        jTblEmpreses = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblIncidenciesEmpresa = new javax.swing.JTable();
        jLblMantenimentEmpreses = new javax.swing.JLabel();
        jBtnAfegirEmpresa = new javax.swing.JButton();
        jBtnModificarEmpresa = new javax.swing.JButton();
        jTxtCodiEmpresa = new javax.swing.JTextField();
        jTxtNomEmpresa = new javax.swing.JTextField();
        jTxtSeuEmpresa = new javax.swing.JTextField();
        jLblCodiEmpresa = new javax.swing.JLabel();
        jLblNom = new javax.swing.JLabel();
        jLblSeu = new javax.swing.JLabel();
        jLblIncidenciesEmpresa = new javax.swing.JLabel();
        jBtnEsborrarEmpresa = new javax.swing.JButton();
        jPnlIncidencies = new javax.swing.JPanel();
        jLblMantenimentIncidencies = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblModels = new javax.swing.JTable();
        jCmbEmpreses = new javax.swing.JComboBox();
        jLblEmpresa = new javax.swing.JLabel();
        jLblReferenciaIncidencia = new javax.swing.JLabel();
        jTxtReferenciaIncidencia = new javax.swing.JTextField();
        jTxtDescripcio = new javax.swing.JTextField();
        jLblDescripcio = new javax.swing.JLabel();
        jTxtCost = new javax.swing.JTextField();
        jLblCost = new javax.swing.JLabel();
        jBtnCercarReferenciaIncidencia = new javax.swing.JButton();
        jLblKmEmail = new javax.swing.JLabel();
        jLblTelefon = new javax.swing.JLabel();
        jTxtTelefon = new javax.swing.JTextField();
        jTxtKmEmail = new javax.swing.JTextField();
        jBtnAltaIncidenciaUrgente = new javax.swing.JButton();
        jBtnAltaIncidenciaEstandar = new javax.swing.JButton();
        jBtnEsborrar = new javax.swing.JButton();
        jBtnModificarIncidencia = new javax.swing.JButton();
        jPnlConsultaIncidenciesEmpresa = new javax.swing.JPanel();
        jLblConsulta = new javax.swing.JLabel();
        jLblSeuConsulta = new javax.swing.JLabel();
        jTxtSeuConsulta = new javax.swing.JTextField();
        jBtnConsulta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblModelsConsultats = new javax.swing.JTable();
        jPnlActualitzacioCostos = new javax.swing.JPanel();
        jLblActualitzacioCost = new javax.swing.JLabel();
        jLblMarcaAActualitzar = new javax.swing.JLabel();
        jBtnActualitza = new javax.swing.JButton();
        jLblTantPerCentActualitzacio1 = new javax.swing.JLabel();
        jTxtTantPerCentAActualitzar = new javax.swing.JTextField();
        jCmbEmpresesActualitzacio = new javax.swing.JComboBox();
        jLblTitolPrincipal = new javax.swing.JLabel();
        jBtnRefrescar = new javax.swing.JButton();
        jBtnGravarCanvis = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPnlEmpreses.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPnlEmpresesComponentShown(evt);
            }
        });

        jTblEmpreses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblEmpreses.setColumnSelectionAllowed(true);
        jTblEmpreses.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrPnlEmpreses.setViewportView(jTblEmpreses);
        jTblEmpreses.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jTblIncidenciesEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTblIncidenciesEmpresa);

        jLblMantenimentEmpreses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblMantenimentEmpreses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMantenimentEmpreses.setText("Gestió d'empreses client");
        jLblMantenimentEmpreses.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jBtnAfegirEmpresa.setText("+");
        jBtnAfegirEmpresa.setToolTipText("Afegir marca");
        jBtnAfegirEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAfegirEmpresaActionPerformed(evt);
            }
        });

        jBtnModificarEmpresa.setText("Modificar");
        jBtnModificarEmpresa.setToolTipText("Modificar empresa");
        jBtnModificarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarEmpresaActionPerformed(evt);
            }
        });

        jTxtCodiEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCodiEmpresaActionPerformed(evt);
            }
        });

        jTxtNomEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomEmpresaActionPerformed(evt);
            }
        });

        jLblCodiEmpresa.setText("Codi");

        jLblNom.setText("Nom");

        jLblSeu.setText("Domicili");

        jLblIncidenciesEmpresa.setText("Incidencies empresa");
        jLblIncidenciesEmpresa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jBtnEsborrarEmpresa.setText("-");
        jBtnEsborrarEmpresa.setToolTipText("Esborrar marca");
        jBtnEsborrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEsborrarEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlEmpresesLayout = new javax.swing.GroupLayout(jPnlEmpreses);
        jPnlEmpreses.setLayout(jPnlEmpresesLayout);
        jPnlEmpresesLayout.setHorizontalGroup(
            jPnlEmpresesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEmpresesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlEmpresesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlEmpresesLayout.createSequentialGroup()
                        .addGroup(jPnlEmpresesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlEmpresesLayout.createSequentialGroup()
                                .addComponent(jLblSeu)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtSeuEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnModificarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addComponent(jScrPnlEmpreses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                            .addComponent(jLblMantenimentEmpreses, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlEmpresesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLblIncidenciesEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(491, 491, 491))
                    .addGroup(jPnlEmpresesLayout.createSequentialGroup()
                        .addComponent(jLblCodiEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtCodiEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLblNom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtNomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAfegirEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnEsborrarEmpresa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPnlEmpresesLayout.setVerticalGroup(
            jPnlEmpresesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlEmpresesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblMantenimentEmpreses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrPnlEmpreses, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPnlEmpresesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCodiEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCodiEmpresa)
                    .addComponent(jLblNom)
                    .addComponent(jTxtNomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAfegirEmpresa)
                    .addComponent(jBtnEsborrarEmpresa))
                .addGap(1, 1, 1)
                .addGroup(jPnlEmpresesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSeu)
                    .addComponent(jTxtSeuEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnModificarEmpresa))
                .addGap(18, 18, 18)
                .addComponent(jLblIncidenciesEmpresa)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        jTpnlPrincipal.addTab("Empreses", jPnlEmpreses);

        jPnlIncidencies.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPnlIncidenciesComponentShown(evt);
            }
        });

        jLblMantenimentIncidencies.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblMantenimentIncidencies.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMantenimentIncidencies.setText("Gestió Incidències");
        jLblMantenimentIncidencies.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTblModels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTblModels);

        jCmbEmpreses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbEmpresesActionPerformed(evt);
            }
        });

        jLblEmpresa.setText("Empresa");

        jLblReferenciaIncidencia.setText("Ref");

        jTxtReferenciaIncidencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtReferenciaIncidenciaFocusLost(evt);
            }
        });

        jLblDescripcio.setText("Descripcio");

        jLblCost.setText("Cost");

        jBtnCercarReferenciaIncidencia.setText("Cercar");
        jBtnCercarReferenciaIncidencia.setToolTipText("Cercar un model a partir del seu alies");
        jBtnCercarReferenciaIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCercarReferenciaIncidenciaActionPerformed(evt);
            }
        });

        jLblKmEmail.setText("Correu electrònic");

        jLblTelefon.setText("Telefon");

        jTxtTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTelefonActionPerformed(evt);
            }
        });

        jBtnAltaIncidenciaUrgente.setText("Registrar Incidencia Urgent");
        jBtnAltaIncidenciaUrgente.setToolTipText("");
        jBtnAltaIncidenciaUrgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAltaIncidenciaUrgenteActionPerformed(evt);
            }
        });

        jBtnAltaIncidenciaEstandar.setText("Registrar Incidencia Estandar");
        jBtnAltaIncidenciaEstandar.setToolTipText("");
        jBtnAltaIncidenciaEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAltaIncidenciaEstandarActionPerformed(evt);
            }
        });

        jBtnEsborrar.setText("Esborrar");
        jBtnEsborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEsborrarActionPerformed(evt);
            }
        });

        jBtnModificarIncidencia.setText("Modificar");
        jBtnModificarIncidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarIncidenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlIncidenciesLayout = new javax.swing.GroupLayout(jPnlIncidencies);
        jPnlIncidencies.setLayout(jPnlIncidenciesLayout);
        jPnlIncidenciesLayout.setHorizontalGroup(
            jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlIncidenciesLayout.createSequentialGroup()
                .addGroup(jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblMantenimentIncidencies, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlIncidenciesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPnlIncidenciesLayout.createSequentialGroup()
                                    .addGroup(jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPnlIncidenciesLayout.createSequentialGroup()
                                            .addComponent(jLblReferenciaIncidencia)
                                            .addGap(11, 11, 11)
                                            .addComponent(jTxtReferenciaIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jBtnCercarReferenciaIncidencia)
                                            .addGap(33, 33, 33)
                                            .addComponent(jLblEmpresa))
                                        .addGroup(jPnlIncidenciesLayout.createSequentialGroup()
                                            .addComponent(jLblDescripcio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTxtDescripcio, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLblCost)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTxtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCmbEmpreses, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPnlIncidenciesLayout.createSequentialGroup()
                                            .addComponent(jBtnModificarIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jBtnEsborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnlIncidenciesLayout.createSequentialGroup()
                                    .addComponent(jLblKmEmail)
                                    .addGap(30, 30, 30)
                                    .addComponent(jTxtKmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnlIncidenciesLayout.createSequentialGroup()
                                    .addGap(190, 190, 190)
                                    .addComponent(jBtnAltaIncidenciaEstandar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPnlIncidenciesLayout.createSequentialGroup()
                                .addComponent(jLblTelefon)
                                .addGap(76, 76, 76)
                                .addComponent(jTxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnAltaIncidenciaUrgente)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPnlIncidenciesLayout.setVerticalGroup(
            jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlIncidenciesLayout.createSequentialGroup()
                .addComponent(jLblMantenimentIncidencies)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblReferenciaIncidencia)
                    .addComponent(jTxtReferenciaIncidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCercarReferenciaIncidencia)
                    .addComponent(jLblEmpresa)
                    .addComponent(jCmbEmpreses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtDescripcio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblDescripcio)
                    .addComponent(jTxtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCost)
                    .addComponent(jBtnModificarIncidencia)
                    .addComponent(jBtnEsborrar))
                .addGap(35, 35, 35)
                .addGroup(jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTelefon)
                    .addComponent(jTxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAltaIncidenciaUrgente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnlIncidenciesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblKmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtKmEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAltaIncidenciaEstandar))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        jTpnlPrincipal.addTab("Incidencies", jPnlIncidencies);

        jLblConsulta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblConsulta.setText("Consulta d' incidències per empresa");
        jLblConsulta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLblSeuConsulta.setText("Nom de la empresa a consultar");

        jBtnConsulta.setText("Fes la consulta");
        jBtnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConsultaActionPerformed(evt);
            }
        });

        jTblModelsConsultats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTblModelsConsultats);

        javax.swing.GroupLayout jPnlConsultaIncidenciesEmpresaLayout = new javax.swing.GroupLayout(jPnlConsultaIncidenciesEmpresa);
        jPnlConsultaIncidenciesEmpresa.setLayout(jPnlConsultaIncidenciesEmpresaLayout);
        jPnlConsultaIncidenciesEmpresaLayout.setHorizontalGroup(
            jPnlConsultaIncidenciesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlConsultaIncidenciesEmpresaLayout.createSequentialGroup()
                .addComponent(jLblConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPnlConsultaIncidenciesEmpresaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLblSeuConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtSeuConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnConsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPnlConsultaIncidenciesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPnlConsultaIncidenciesEmpresaLayout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );
        jPnlConsultaIncidenciesEmpresaLayout.setVerticalGroup(
            jPnlConsultaIncidenciesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlConsultaIncidenciesEmpresaLayout.createSequentialGroup()
                .addComponent(jLblConsulta)
                .addGap(26, 26, 26)
                .addGroup(jPnlConsultaIncidenciesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblSeuConsulta)
                    .addComponent(jTxtSeuConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnConsulta))
                .addGap(0, 409, Short.MAX_VALUE))
            .addGroup(jPnlConsultaIncidenciesEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPnlConsultaIncidenciesEmpresaLayout.createSequentialGroup()
                    .addGap(87, 87, 87)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE)))
        );

        jTpnlPrincipal.addTab("Consulta", jPnlConsultaIncidenciesEmpresa);

        jPnlActualitzacioCostos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPnlActualitzacioCostosComponentShown(evt);
            }
        });

        jLblActualitzacioCost.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLblActualitzacioCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblActualitzacioCost.setText("Actualització cost");
        jLblActualitzacioCost.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLblMarcaAActualitzar.setText("Empresa a actualitzar");

        jBtnActualitza.setText("Actualitza");
        jBtnActualitza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActualitzaActionPerformed(evt);
            }
        });

        jLblTantPerCentActualitzacio1.setText("% del cost a actualitzar");

        jCmbEmpresesActualitzacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmbEmpresesActualitzacioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlActualitzacioCostosLayout = new javax.swing.GroupLayout(jPnlActualitzacioCostos);
        jPnlActualitzacioCostos.setLayout(jPnlActualitzacioCostosLayout);
        jPnlActualitzacioCostosLayout.setHorizontalGroup(
            jPnlActualitzacioCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlActualitzacioCostosLayout.createSequentialGroup()
                .addComponent(jLblActualitzacioCost, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPnlActualitzacioCostosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPnlActualitzacioCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblMarcaAActualitzar)
                    .addGroup(jPnlActualitzacioCostosLayout.createSequentialGroup()
                        .addComponent(jLblTantPerCentActualitzacio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPnlActualitzacioCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCmbEmpresesActualitzacio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtTantPerCentAActualitzar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jBtnActualitza)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlActualitzacioCostosLayout.setVerticalGroup(
            jPnlActualitzacioCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlActualitzacioCostosLayout.createSequentialGroup()
                .addComponent(jLblActualitzacioCost)
                .addGap(30, 30, 30)
                .addGroup(jPnlActualitzacioCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbEmpresesActualitzacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblMarcaAActualitzar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnlActualitzacioCostosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtTantPerCentAActualitzar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblTantPerCentActualitzacio1)
                    .addComponent(jBtnActualitza))
                .addGap(0, 374, Short.MAX_VALUE))
        );

        jTpnlPrincipal.addTab("Actualitzacio Cost", jPnlActualitzacioCostos);

        jLblTitolPrincipal.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLblTitolPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitolPrincipal.setText("Manteniment d' Incidencies");
        jLblTitolPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLblTitolPrincipal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jBtnRefrescar.setText("Refrescar");
        jBtnRefrescar.setToolTipText("Recupera les dades de la BD sense salvar canvis no gravats");
        jBtnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRefrescarActionPerformed(evt);
            }
        });

        jBtnGravarCanvis.setText("Gravar canvis");
        jBtnGravarCanvis.setToolTipText("Gravar canvis no desats");
        jBtnGravarCanvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGravarCanvisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblTitolPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 24, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jBtnRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnGravarCanvis, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLblTitolPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRefrescar)
                    .addComponent(jBtnGravarCanvis))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnModificarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarEmpresaActionPerformed
        if(empresaAMantenir==null){
            avis("No has seleccionat cap empresa");
        }else{
            try {
                carregarCampsEmpresa();
                bd.modificar(empresaAMantenir);
                empresaAMantenir=null;
                netejarCampsEmpresa();
                refrescarEmpreses();
                
            } catch (UtilitatPersistenciaException ex) {
                Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }        
    }//GEN-LAST:event_jBtnModificarEmpresaActionPerformed

    private void jBtnAfegirEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAfegirEmpresaActionPerformed
            
        String codi = jTxtCodiEmpresa.getText().trim();
        
        if(codi.isEmpty()){
            avis("Cal entrar l'codi");
        }else{
            
                try {
                     empresaAMantenir = bd.nouEmpresaTemporal(codi);
                } catch (UtilitatPersistenciaException ex) {
                    Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
                }
                empresaAMantenir.setCodi(codi);
                carregarCampsEmpresa();
                try {
                    bd.inserir(empresaAMantenir);
                    
                    refrescarEmpreses();
                } catch (UtilitatPersistenciaException ex) {
                    Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
                }
                empresaAMantenir=null;
                netejarCampsEmpresa();
        }
            
            
    }//GEN-LAST:event_jBtnAfegirEmpresaActionPerformed

    private void jBtnGravarCanvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGravarCanvisActionPerformed
        try {
            bd.gravaCanvis();
            jTpnlPrincipal.getSelectedComponent().setVisible(true);
        } catch (UtilitatPersistenciaException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnGravarCanvisActionPerformed

    private void jPnlEmpresesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPnlEmpresesComponentShown
        refrescarEmpreses();
    }//GEN-LAST:event_jPnlEmpresesComponentShown

    private void jBtnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRefrescarActionPerformed
        try {
            bd.anullaCanvis();
            for(ComponentListener c:jTpnlPrincipal.getSelectedComponent().getComponentListeners()){
                if (c instanceof ComponentAdapter){
                    ((ComponentAdapter)c).componentShown(null);
                }
            }
            jTpnlPrincipal.getSelectedComponent().setVisible(true);
        } catch (UtilitatPersistenciaException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnRefrescarActionPerformed

    private void jBtnEsborrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEsborrarEmpresaActionPerformed
        if(empresaAMantenir==null){
            avis("No has seleccionat cap empresa");
            
        }else if(!empresaAMantenir.getLlistaIncidencies().isEmpty()){
            avis("L' empresa té incidencies");
        }else{
            try {
                bd.eliminar(empresaAMantenir);
                empresaAMantenir=null;
                netejarCampsEmpresa();
                refrescarEmpreses();
            } catch (UtilitatPersistenciaException ex) {
                Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jBtnEsborrarEmpresaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            bd.anullaCanvis();
            bd.tancar();
        } catch (UtilitatPersistenciaException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jBtnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConsultaActionPerformed
        this.refrescarConsultaIncidencies();
    }//GEN-LAST:event_jBtnConsultaActionPerformed

    private void jBtnActualitzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActualitzaActionPerformed
         float tantPerCent;
         String cadenaTantPerCent;
         Empresa m;

        // comprovacio parametres. Sortida si no son correctes
         
         
         cadenaTantPerCent=jTxtTantPerCentAActualitzar.getText().trim();
         if (cadenaTantPerCent.isEmpty()){
             avis("Falta entrar el tant per cent");
             return;
         }
         
         try{
             tantPerCent=new Float(cadenaTantPerCent);
         }catch(NumberFormatException e){
             avis("Format del percentatge erroni");
             return;
         }
         
         m=(Empresa)jCmbEmpresesActualitzacio.getSelectedItem();
         if (m==null){
             avis("Falta entarar l'empresa");
             return;
         }
         
         
        // realitzacio de l'actualitzacio
        try {
            bd.modificarCostResolucioIncidencia(m.getNomEmpresa(), tantPerCent);
             //xx  bd.modificarPreuModelsMarca(m.getCodi(), tantPerCent);
        } catch (UtilitatPersistenciaException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jBtnActualitzaActionPerformed

    private void jPnlActualitzacioCostosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPnlActualitzacioCostosComponentShown
        refrescarEmpresesActualitzacio();
    }//GEN-LAST:event_jPnlActualitzacioCostosComponentShown

    private void jTxtCodiEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCodiEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCodiEmpresaActionPerformed

    private void jTxtNomEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomEmpresaActionPerformed

    private void jCmbEmpresesActualitzacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbEmpresesActualitzacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbEmpresesActualitzacioActionPerformed

    private void jPnlIncidenciesComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPnlIncidenciesComponentShown
        refrescarIncidencies();
    }//GEN-LAST:event_jPnlIncidenciesComponentShown

    private void jBtnModificarIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarIncidenciaActionPerformed
        if(copiaCampsEmpresa()){
            try {
                bd.modificar(incidenciaAMantenir);
            } catch (UtilitatPersistenciaException ex) {
                Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                incidenciaAMantenir=null;
                netejarCampsIncidencia();
                activarCampsIncidencia();
                refrescarIncidencies();
            }
        }

    }//GEN-LAST:event_jBtnModificarIncidenciaActionPerformed

    private void jBtnEsborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEsborrarActionPerformed
        String codi = jTxtReferenciaIncidencia.getText().trim();

        if(codi.isEmpty()){
            avis("No has entrat l'codi. Baixa no realitzada");
        }

        try {
            bd.eliminar(incidenciaAMantenir);
        } catch (UtilitatPersistenciaException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            incidenciaAMantenir=null;
            netejarCampsIncidencia();
            activarCampsIncidencia();
            refrescarIncidencies();
        }

    }//GEN-LAST:event_jBtnEsborrarActionPerformed

    private void jBtnAltaIncidenciaEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAltaIncidenciaEstandarActionPerformed
        try {
            incidenciaAMantenir=bd.novaIncidenciaEstandarTemporal(null);
        } catch (UtilitatPersistenciaException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(copiaCampsEmpresa()){
            try {
                bd.inserir(incidenciaAMantenir);
            } catch (UtilitatPersistenciaException ex) {
                Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                incidenciaAMantenir=null;
                netejarCampsIncidencia();
                refrescarIncidencies();
            }
        }
    }//GEN-LAST:event_jBtnAltaIncidenciaEstandarActionPerformed

    private void jBtnAltaIncidenciaUrgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAltaIncidenciaUrgenteActionPerformed
        try {
            incidenciaAMantenir=bd.novaIncidenciaUrgentTemporal(null);
        } catch (UtilitatPersistenciaException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(copiaCampsEmpresa()){
            try {
                bd.inserir(incidenciaAMantenir);
            } catch (UtilitatPersistenciaException ex) {
                Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                incidenciaAMantenir=null;
                netejarCampsIncidencia();
                refrescarIncidencies();
            }
        }
    }//GEN-LAST:event_jBtnAltaIncidenciaUrgenteActionPerformed

    private void jTxtTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTelefonActionPerformed

    private void jBtnCercarReferenciaIncidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCercarReferenciaIncidenciaActionPerformed
        try {
            Boolean esIncidenciaUrgent, esIncidenciaEstandar;

            incidenciaAMantenir = bd.obtenirIncidencia(jTxtReferenciaIncidencia.getText().trim());

            jTxtDescripcio.setText(incidenciaAMantenir.getDescripcio());
            jTxtCost.setText(incidenciaAMantenir.getCost()+"");
            jCmbEmpreses.setSelectedItem(incidenciaAMantenir.getEmpresa());

            esIncidenciaUrgent=(incidenciaAMantenir instanceof IncidenciaUrgent);

            esIncidenciaEstandar=(incidenciaAMantenir instanceof IncidenciaEstandar);

            jTxtTelefon.setEnabled(esIncidenciaUrgent);
            jTxtKmEmail.setEnabled(esIncidenciaEstandar);
            jBtnAltaIncidenciaUrgente.setEnabled(esIncidenciaUrgent);
            jBtnAltaIncidenciaEstandar.setEnabled(esIncidenciaEstandar);

            if(esIncidenciaUrgent){
                IncidenciaUrgent auxModel=(IncidenciaUrgent)incidenciaAMantenir;
                //xx jTxtConsum100Km.setText(auxModel.getConsum100Km()+"");
                jTxtTelefon.setText(auxModel.getTelefon());
            }else if(esIncidenciaEstandar){
                IncidenciaEstandar auxModel=(IncidenciaEstandar)incidenciaAMantenir;
                //xx jTxtKmAutonomia.setText(auxModel.getKmAutonomia()+"");
                jTxtKmEmail.setText(auxModel.getEmail());
            }

            jCmbEmpreses.repaint();

        } catch (UtilitatPersistenciaException ex) {
            // no existeix la incidencia buscada
        }
    }//GEN-LAST:event_jBtnCercarReferenciaIncidenciaActionPerformed

    private void jTxtReferenciaIncidenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtReferenciaIncidenciaFocusLost

        if(incidenciaAMantenir!=null && ! (incidenciaAMantenir.getReferencia().trim().equals(jTxtReferenciaIncidencia.getText().trim()))){
            incidenciaAMantenir=null;
            activarCampsIncidencia();
            netejarCampsIncidencia(false);
            refrescarIncidencies();
        }
    }//GEN-LAST:event_jTxtReferenciaIncidenciaFocusLost

    private void jCmbEmpresesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmbEmpresesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmbEmpresesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnActualitza;
    private javax.swing.JButton jBtnAfegirEmpresa;
    private javax.swing.JButton jBtnAltaIncidenciaEstandar;
    private javax.swing.JButton jBtnAltaIncidenciaUrgente;
    private javax.swing.JButton jBtnCercarReferenciaIncidencia;
    private javax.swing.JButton jBtnConsulta;
    private javax.swing.JButton jBtnEsborrar;
    private javax.swing.JButton jBtnEsborrarEmpresa;
    private javax.swing.JButton jBtnGravarCanvis;
    private javax.swing.JButton jBtnModificarEmpresa;
    private javax.swing.JButton jBtnModificarIncidencia;
    private javax.swing.JButton jBtnRefrescar;
    private javax.swing.JComboBox jCmbEmpreses;
    private javax.swing.JComboBox jCmbEmpresesActualitzacio;
    private javax.swing.JLabel jLblActualitzacioCost;
    private javax.swing.JLabel jLblCodiEmpresa;
    private javax.swing.JLabel jLblConsulta;
    private javax.swing.JLabel jLblCost;
    private javax.swing.JLabel jLblDescripcio;
    private javax.swing.JLabel jLblEmpresa;
    private javax.swing.JLabel jLblIncidenciesEmpresa;
    private javax.swing.JLabel jLblKmEmail;
    private javax.swing.JLabel jLblMantenimentEmpreses;
    private javax.swing.JLabel jLblMantenimentIncidencies;
    private javax.swing.JLabel jLblMarcaAActualitzar;
    private javax.swing.JLabel jLblNom;
    private javax.swing.JLabel jLblReferenciaIncidencia;
    private javax.swing.JLabel jLblSeu;
    private javax.swing.JLabel jLblSeuConsulta;
    private javax.swing.JLabel jLblTantPerCentActualitzacio1;
    private javax.swing.JLabel jLblTelefon;
    private javax.swing.JLabel jLblTitolPrincipal;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel jPnlActualitzacioCostos;
    private javax.swing.JPanel jPnlConsultaIncidenciesEmpresa;
    private javax.swing.JPanel jPnlEmpreses;
    private javax.swing.JPanel jPnlIncidencies;
    private javax.swing.JScrollPane jScrPnlEmpreses;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTblEmpreses;
    private javax.swing.JTable jTblIncidenciesEmpresa;
    private javax.swing.JTable jTblModels;
    private javax.swing.JTable jTblModelsConsultats;
    private javax.swing.JTabbedPane jTpnlPrincipal;
    private javax.swing.JTextField jTxtCodiEmpresa;
    private javax.swing.JTextField jTxtCost;
    private javax.swing.JTextField jTxtDescripcio;
    private javax.swing.JTextField jTxtKmEmail;
    private javax.swing.JTextField jTxtNomEmpresa;
    private javax.swing.JTextField jTxtReferenciaIncidencia;
    private javax.swing.JTextField jTxtSeuConsulta;
    private javax.swing.JTextField jTxtSeuEmpresa;
    private javax.swing.JTextField jTxtTantPerCentAActualitzar;
    private javax.swing.JTextField jTxtTelefon;
    // End of variables declaration//GEN-END:variables

    private void refrescarEmpreses() {
        try {
            
            jTblEmpreses.setModel(new ModelTaulaList<Empresa>(bd.obtenirEmpresasOrdenatsPerNomEmpresa(),
                    Empresa.class, new String[]{"Cod. Empresa","Nom Empresa","Seu Empresa"}, new String[][]{{"codi"},{"nomEmpresa"},{"seuEmpresa"}}));
            
            jTblEmpreses.repaint();
        } catch (UtilitatPersistenciaException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ModelTaulaListException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    private void refrescarIncidenciesEmpresa() {
        try {
            if(empresaAMantenir!=null){
                jTblIncidenciesEmpresa.setModel(new ModelTaulaList<Incidencia>(empresaAMantenir.getLlistaIncidencies(),
                        Incidencia.class, new String[]{"Ref. Incidencia","Descripcio","Cost","Poblacio"}, new String[][]{{"referencia"},{"descripcio"},{"cost"},{"empresa","seuEmpresa"}}));
              
   
            }else{
                jTblIncidenciesEmpresa.setModel(new ModelTaulaList<Incidencia>(new ArrayList<Incidencia>(),
                        Incidencia.class, new String[]{"Ref. Incidencia","Descripcio","Cost","Poblacio"}, new String[][]{{"referencia"},{"descripcio"},{"cost"},{"empresa","seuEmpresa"}}));
                        
            }
            jTblIncidenciesEmpresa.repaint();
        
        } catch (ModelTaulaListException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void refrescarIncidencies(){

        try {
       
            jTblModels.setModel(new ModelTaulaList<Incidencia>(bd.obtenirIncidenciesOrdenadesPerReferencia(),
                        Incidencia.class, new String[]{"Ref. Incidencia","Empresa","Descripció","Cost"}, 
                    
                    new String[][]{{"referencia"},{"empresa","nomEmpresa"},{"descripcio"},{"cost"}}));
            jTblModels.repaint();
            jCmbEmpreses.setModel(new ModelComboList<Empresa>(bd.obtenirEmpresasOrdenatsPerNomEmpresa()));
            jCmbEmpreses.repaint();
        } catch (UtilitatPersistenciaException | ModelTaulaListException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }

    
    }
    
    private void refrescarEmpresesActualitzacio() {
        try {
            jCmbEmpresesActualitzacio.setModel(new ModelComboList<Empresa>(bd.obtenirEmpresasOrdenatsPerNomEmpresa()));
            jCmbEmpresesActualitzacio.repaint();
        } catch (UtilitatPersistenciaException  ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    
    private void refrescarConsultaIncidencies(){

        try {
            String seu = this.jTxtSeuConsulta.getText();
            if(seu.isEmpty()){
                jTblModelsConsultats.setModel(new ModelTaulaList<Incidencia>(new ArrayList<Incidencia>(),
                        Incidencia.class, new String[]{"Referencia","Descripcio","Cost","Domicili"}, new String[][]{{"referencia"},{"descripcio"},{"cost"},{"empresa","seuEmpresa"}}));
            }else {
                jTblModelsConsultats.setModel(new ModelTaulaList<Incidencia>(bd.obtenirIncidenciesPerEmpresa(seu),
                        Incidencia.class, new String[]{"Referencia","Descripcio","Cost","Domicili"}, new String[][]{{"referencia"},{"descripcio"},{"cost"},{"empresa","seuEmpresa"}}));
            }
            jTblModels.repaint();
        } catch (UtilitatPersistenciaException | ModelTaulaListException ex) {
            Logger.getLogger(GestioBD.class.getName()).log(Level.SEVERE, null, ex);
        }

    
    }
    
    
    private void avis(String missatge) {
        JOptionPane.showMessageDialog(this,missatge, "Avis !!!", JOptionPane.WARNING_MESSAGE);
    }    
    
    private void netejarCampsEmpresa(){
        jTxtNomEmpresa.setText("");
        jTxtSeuEmpresa.setText("");
        refrescarIncidenciesEmpresa();
    }

    private void carregarCampsEmpresa() {
        empresaAMantenir.setNomEmpresa(jTxtNomEmpresa.getText().trim());
        empresaAMantenir.setSeuEmpresa(jTxtSeuEmpresa.getText().trim());
        //System.out.println(jTxtNomEmpresa.getText().trim());
    }
    
    private void afegirListenersLiniaSeleccionada() {
        this.jTblEmpreses.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            
            @Override
            public void valueChanged(ListSelectionEvent e) {
                String aux;
                netejarCampsEmpresa();
                jTxtCodiEmpresa.setText(aux=(String)jTblEmpreses.getModel().getValueAt(jTblEmpreses.getSelectedRow(),0));
                Empresa emp;
                try {
                    emp = (Empresa) bd.obtenirEmpresa(aux);
                } catch (UtilitatPersistenciaException ex) {
                    emp=null;
                }
                empresaAMantenir=emp;
                if(emp!=null){
                    jTxtNomEmpresa.setText(emp.getNomEmpresa());
                    jTxtSeuEmpresa.setText(emp.getSeuEmpresa());   
                }               
            }
        });

        this.jTblModels.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e){ 
                netejarCampsIncidencia();
                jTxtReferenciaIncidencia.setText((String)jTblModels.getModel().getValueAt(jTblModels.getSelectedRow(),0));

            }
        });
    
    }

    private boolean copiaCampsEmpresa() {
        
        float preu=0;

        boolean esUrgent, esEstandar;
        String elementComprovat="",telf ="",mail="";
        
        try{
            esUrgent=(incidenciaAMantenir instanceof IncidenciaUrgent);
            esEstandar=(incidenciaAMantenir instanceof IncidenciaEstandar);

            if(esUrgent){
                elementComprovat="El telefon";
                telf = new String(this.jTxtTelefon.getText());
            }

            if(esEstandar){
                elementComprovat="El email";
                mail = new String(this.jTxtKmEmail.getText());
            }
            elementComprovat="El cost";
            preu=new Float(this.jTxtCost.getText());
        
        }catch(NumberFormatException e){
                avis(elementComprovat + " te format incorrecte");
                return false;
        }
            
        if(incidenciaAMantenir.getReferencia()==null){  // es un model nou
            incidenciaAMantenir.setReferencia(jTxtReferenciaIncidencia.getText().trim());
        }
        
        incidenciaAMantenir.setEmpresa((Empresa)(jCmbEmpreses.getSelectedItem()));
        incidenciaAMantenir.setDescripcio(jTxtDescripcio.getText().trim());
        incidenciaAMantenir.setCost(preu);
        
        if(esUrgent){
            IncidenciaUrgent m = (IncidenciaUrgent) incidenciaAMantenir;
            m.setTelefon(telf);
            //m.setConsum100Km(telf);
        }
        if(esEstandar){
            IncidenciaEstandar m = (IncidenciaEstandar) incidenciaAMantenir;
            m.setEmail(mail);
            //m.setKmAutonomia(mail);
            
        }
        return true;
    }

    private void netejarCampsIncidencia(){
        netejarCampsIncidencia(false);
    }
    
    private void netejarCampsIncidencia(boolean netejarReferencia) {
        if(netejarReferencia) {
            jTxtReferenciaIncidencia.setText("");
        }
        jTxtDescripcio.setText("");
        jTxtCost.setText("");
        jCmbEmpreses.setSelectedItem(null);
        jTxtTelefon.setText("");
        jTxtKmEmail.setText("");
    }

    private void activarCampsIncidencia() {
        jTxtTelefon.setEnabled(true);
        jTxtKmEmail.setEnabled(true);
        jBtnAltaIncidenciaUrgente.setEnabled(true);
        jBtnAltaIncidenciaEstandar.setEnabled(true);
    }

    private void adaptarCombosEmpreses() {
        final ListCellRenderer renderOriginalEmpreses= jCmbEmpreses.getRenderer();
        final ListCellRenderer renderOriginalEmpresesAct= jCmbEmpresesActualitzacio.getRenderer();
        
        jCmbEmpreses.setRenderer(new ListCellRenderer(){

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Empresa empresa = (Empresa)value;
                if(empresa!=null){
                    return renderOriginalEmpreses.getListCellRendererComponent(list,noNull(empresa.getNomEmpresa()),index,isSelected,cellHasFocus);
                }
                else return renderOriginalEmpreses.getListCellRendererComponent(list,value,index,isSelected,cellHasFocus);
                
            }
        });
        
        jCmbEmpresesActualitzacio.setRenderer(new ListCellRenderer(){

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                Empresa marca = (Empresa)value;
                if(marca!=null){
                    return renderOriginalEmpresesAct.getListCellRendererComponent(list,noNull(marca.getNomEmpresa()),index,isSelected,cellHasFocus);
                }
                else return renderOriginalEmpresesAct.getListCellRendererComponent(list,value,index,isSelected,cellHasFocus);
                
            }
        });

      
    }

    private String noNull(String s){
        return (s==null?"":s);
    }



}
